name: CI + CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Compile
        run: echo Hello, world!

  DeployDev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: Build
    if: github.event_name == 'pull_request'
    environment:
      name: Development
      url: https://dev.example.com
    steps:
      - name: Deploy
        run: echo I am deploying!

  DeployStaging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: Build
    if: github.ref == 'refs/heads/main'
    environment:
      name: Staging
      url: https://staging.example.com
    steps:
      - name: Deploy
        run: echo I am deploying!

  DeployProd:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: DeployStaging
    environment:
      name: Production
      url: https://example.com
    steps:
      - name: Deploy
        run: echo I am deploying!