name: CI + CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:



  DeployDev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: Build
    if: github.event_name == 'pull_request'
    environment:
      name: development
      url: https://dev.example.com
    steps:
      - name: Deploy
        run: echo I am deploying!

  DeployStaging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: Build
    if: github.ref == 'refs/heads/main'
    environment:
      name: staging
      url: https://staging.example.com
    steps:
      - name: Deploy
        run: echo I am deploying!

  DeployProd:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: DeployStaging
    environment:
      name: production
      url: https://example.com
    steps:
      - name: Deploy
        run: echo I am deploying!